development:
  adapter: postgresql
  encoding: unicode
  database: wdi_4_rails_hw_activerecord_bookmarks_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: wdi_4_rails_hw_activerecord_bookmarks_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: wdi_4_rails_hw_activerecord_bookmarks_production
  pool: 5